name: "Node Continuous Deployment"

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'

jobs:
  build-and-deploy:
    name: "Build e Deploy no Vercel"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout do código"
        uses: actions/checkout@v7

      - name: "Configurar o Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: "Instalar dependências"
        run: npm ci

      - name: "Compilar e buildar o projeto"
        run: npm run build

      - name: "Instalar Vercel CLI"
        run: npm i -g vercel@latest

      - name: "Deploy para Vercel"
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
